name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: ["main", "master"]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 📅 Isometric Calendar
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics/isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          config_timezone: Europe/Istanbul
          config_padding: 0, 8 + 11%

      - name: 📉 Languages (Indepth)
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics/languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, makefile,
            dockerfile, shell
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_limit: 8
          plugin_languages_sections: most-used, recently-used
          plugin_languages_colors: github
          plugin_languages_aliases: ""

      - name: 🏆 Achievements
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics/achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_threshold: B
          plugin_achievements_secrets: yes
          plugin_achievements_display: compact
          plugin_achievements_limit: 0

      - name: 📰 Recent Activity
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics/activity.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: >-
            push, pr, review, ref/create
          plugin_activity_visibility: all
          plugin_activity_timestamps: yes

      - name: ✨ Notable Contributions
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics/notable.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_types: commit
          plugin_notable_indepth: yes

      - name: 👨‍💻 Lines of Code
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics/lines.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: repositories
          plugin_lines: yes
          plugin_lines_history_limit: 1

      - name: 💡 Coding Habits
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics/habits.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: chartist